function(check_and_set_flag flag_name macro_name)
    check_cxx_compiler_flag(${flag_name} ${macro_name})
    if(${macro_name})
        add_compile_options(${flag_name})
        add_definitions(-D${macro_name})
    endif()
endfunction()

if(NOT CMAKE_SYSTEM_PROCESSOR MATCHES "arm*|aarch64*")
    # Only add AVX512 if the target CPU supports it and it's necessary
    check_and_set_flag("-mavx2" HAS_MAVX2)
    check_and_set_flag("-msse4.2" HAS_MSSE4_2)
else()
    add_definitions(-DHAS_MFPU_NEON)
endif()